# Generated by Django 4.1.4 on 2022-12-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('budget', models.IntegerField(default=1000)),
                ('cpu_brand', models.CharField(default='', max_length=5)),
                ('gpu_brand', models.CharField(default='', max_length=7)),
                ('cooler_type', models.CharField(default='AIR', max_length=6)),
                ('cpu', models.CharField(default='', max_length=100)),
                ('gpu', models.CharField(default='', max_length=100)),
                ('ram', models.CharField(default='', max_length=100)),
                ('mb', models.CharField(default='', max_length=100)),
                ('case', models.CharField(default='', max_length=100)),
                ('psu', models.CharField(default='', max_length=100)),
                ('storage', models.CharField(default='', max_length=100)),
                ('cooler', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
