# Generated by Django 4.1.4 on 2022-12-19 23:00

from django.db import migrations

def create_data(apps, schema_editor):
    Build = apps.get_model('evolutionary_builder', 'Build')
    Build(budget=1000, cpu_brand="AMD", gpu_brand="GeForce", cooler_type="LIQUID",
          cpu="AMD Ryzen 7 5800X", gpu="GeForce 3060ti", ram="Corsair",
          mb="NZXT b550", case="HYTE", psu="Corsair", storage="980",
          cooler="NZXT Z73").save()

class Migration(migrations.Migration):

    dependencies = [
        ('evolutionary_builder', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
