# Generated by Django 3.2.5 on 2022-10-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builds',
            name='aio_pref',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
